# Generated by Django 2.2.5 on 2019-09-22 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='CPF',
            new_name='cpf',
        ),
    ]
